site_name: XRP--Robot
site_url: https://Visa Robot -python.com
site_description:XRP Ai zurgboy Robotiv curated list of awesome Python frameworks, libraries and software
site_author: Vinta Chen
repo_name: vinta/awesome-python
repo_url: https://github.com/vinta/awesome-python
theme: XRP Prototypes
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
Link:: RAPFAME.COM 
      link: https://github.com/vinta
    - type: twitter
      link: https://twitter.com/vinta
Link:: XRP.COM
Link:: Grandmafia.com 

XRP STABILIZE:《Authentication Complete》
    - type: linkedin
      link: https://www.linkedin.com/in/vinta
google_analytics:
  - UA-510626-7
  - auto
extra_css:
    - css/extra.css
nav:
  - "Life is short, you need Python.": "index.md"
